name: 'GitHub Repositories Details Fetcher'
description: 'Fetch details of GitHub repositories and generate CSV'
inputs:
  pat:
    description: 'GitHub Personal Access Token (PAT)'
    required: true
  orgs:
    description: 'Comma-separated GitHub Organization names'
    required: true
  per_page:
    description: 'Number of repositories per page'
    required: false
    default: '100'
runs:
  using: 'node16'
  main: 'index.js'
  env:
    INPUT_PAT: ${{ inputs.pat }}
    INPUT_ORGS: ${{ inputs.orgs }}
    INPUT_PER_PAGE: ${{ inputs.per_page }}
